### ISSUE TITLE
Bug: Users are able to view machines in other groups

### ISSUE THREAD

**Issue by tedtms** [lucent-sea/Remotely#181]
Good morning,

I've run into a bug where machines that are in set groups are visible to users outside of that group. Example, I have a "Personal" group of machines where I am the only user with access, but when I add a coworker to my server and assign them to my "Work" group of machines, he can also see my Personal machines if he selects "All" from the group drop-down.

However, the coworker user can only **control** machines within his group. He cannot edit the information or perform remote control for machines in my Personal group. Still, I imagine it's preferred to not have unauthorized users see machines outside of their groups at all?

I'm running 2020.11.25.1712 on Ubuntu 20.04.

Thanks!
Ted

**Comment by lucent-sea** [comment]
Thanks for bringing this to my attention.  It's being addressed in the following branch: https://github.com/lucent-sea/Remotely/tree/many-to-many-refactor

I still need to test it some more since it incorporates some pretty major changes for new .NET 5 features.

**Comment by lucent-sea** [comment]
Well, I haven't heard any reports of catastrophic failure since I merged it in, and the public server is working.  I'll call this good for now.

**Comment by tedtms** [comment]
No catastrophic failure, but even after updating to the 12.06 build I'm still experiencing the same issue. Users outside of the assigned group for machines still see those machines in their All list when looking at the main interface.

**Comment by tedtms** [comment]
Great, after updating and re-assigning the groups, things to be working normally. Thanks!
